### ISSUE TITLE
Error message when executing "steinbock measure intensities"

### ISSUE THREAD

**Issue by marleneweiss** [BodenmillerGroup/steinbock#177] opened 2023-03-27 16:12 UTC
Hi,

I have been working with steinbock since the workshop and it has been great. However, when executing "steinbock measure intensities" for new samples, I got the error message copied below. Could you maybe hint me towards what the problem might be? The commands for preprocessing, measuring neighbors and regionprops for the same samples worked without an issue. Thank you, Marlene
![Error_measure intensities](https://user-images.githubusercontent.com/122556489/227998950-a034475d-7b50-4295-babb-a10c026613f8.png)

**Comment by marleneweiss** [comment] 2023-03-30 19:28
Hi Milad,

thank you for your answer and for hinting me towards the underlying issue. I am not sure what was wrong with the old panel file (it did not have an extra channel in it), but I exchanged it and then it worked.

Best,
Marlene

**Comment by Milad4849** [comment] 2023-03-31 11:35
Hi Marlene, 
I am glad that your issue was solved. I am still wondering about the root cause. Could you please tell me how the two panel files are different and whether you redid the whole analysis after swapping back the old panel file?

regards, 
Milad

**Comment by Milad4849** [comment] 2023-04-25 08:25
closing the issue.

**Closed by Milad4849** 2023-04-25 08:25 UTC
