### ISSUE TITLE
Segmentation issues 

### ISSUE THREAD

**Issue by KHALILISAEED** [BodenmillerGroup/steinbock#153] opened 2022-11-01 20:20 UTC
There are few issues running steinbock:
Once I have # Select a random image
rng = np.random.default_rng()
ix = rng.choice(len(segstacks))
I see a value error (ValueError: a must be a positive integer unless no samples are taken)
Additionally, ModuleNotFoundError: No module named 'deepcell_toolbox'
And in preprocessing I see NameError: name 'Acquisition' is not defined.
If you can help, it would be great. 

Best,
Saeed

**Comment by jwindhager** [comment] 2022-11-01 20:30
Hi @KHALILISAEED, thanks for reaching out. From @nilseling I understand that you're using steinbock v0.15. Could you please post the exact script/command you're trying to run? And, if you're using the steinbock Docker container (recommended), the `steinbock` command alias? Thanks

**Comment by KHALILISAEED** [comment] 2022-11-02 00:21
I have installed steinbock through Python  (not docker). I copied your Steinbock repository into colab google, chose examples under Branch, and then select and copied all codes from 01preprocessing_if, 01preprocessing_imc, 02segmentation_deepcell and 03 measurement paste into jupyter notebook. I have practically used all of the codes from these 4 examples. Please see the attached and let me know if you have any question. I appreciate your help. 
<img width="843" alt="Screenshot 2022-11-01 at 8 16 27 PM" src="https://user-images.githubusercontent.com/108760161/199365856-59e75ec1-b072-4253-a618-44d27787c7a5.png">

Best

**Comment by jwindhager** [comment] 2022-11-02 05:32
Please note that #135 has not been merged into `main` and that we therefore do not fully support scripts from the `examples` branch at this point. However, the scripts will likely be reviewed and merged over the coming two weeks. In the meantime, their main author, @ndamond, may be able to help.

**Comment by ndamond** [comment] 2022-11-02 07:33
Hi @KHALILISAEED,

As @jwindhager mentioned, the jupyter scripts are not finalized yet. The standard way to use `steinbock` is currently to use docker: https://bodenmillergroup.github.io/steinbock/latest/install-docker/

If you still want to use the notebooks:
- Note that the `01_preprocessing_if` notebook is not usable yet.
- Can you describe how you installed the python libraries in google colab?
- After the installation, could you paste the output of `!pip list -v` here?
- The error you see is caused by an empty image list. After running after running the first script (`01_preprocessing_imc`), can you check if the folder tree below is being generated? And can you check the content of the `img` subfolder?
```
steinbock data/working directory
├── raw
 |    └── *.zip (raw data)
├── img
├── segstacks
├── masks
├── intensities
├── regionprops
└── neighbors
```

Best,
Nicolas

**Comment by KHALILISAEED** [comment] 2022-11-02 11:26
Hi Nicolas and team members:
Thanks so much for getting back to me so quickly with your feedback and
comments. I am not a data scientist!I only took a course for basic python
as a Stem Cell Biologist and started using it. Regarding docket, I do not
know how to use it. Is there a page or simple step by step setting up
docker document where I can learn and use it. It would mean a lot to me if
you can help me with that. I can start using it today. We are a group at U
of T in Toronto, Canada alongside a few others who use IMC (Vincent Piguet
Lab).
I only used colab to reveal the codes and then copy and paste the codes
into a new jupyter notebook and started running them. I have not run any
script or installed any package in the colab directly.

I will go through your comments when I get to the lab. Many thanks.

Best,
Saeed

**Comment by nilseling** [comment] 2022-11-02 11:45
Hi @KHALILISAEED, 

have a look at the documentation of `steinbock` [here](https://bodenmillergroup.github.io/steinbock/latest/cli/intro/). 

Please zip each MCD + related TXT files and place all ZIP files in the folder `/path/to/data/raw`. When docker is installed and running (see [installation instructions](https://docs.docker.com/get-docker/)) you define an alias in the command line via (e.g. for Mac):

```
alias steinbock="docker run -v /path/to/data:/data -v /tmp/.X11-unix:/tmp/.X11-unix -v ~/.Xauthority:/home/steinbock/.Xauthority:ro -u $(id -u):$(id -g) -e DISPLAY=$(hostname):0 ghcr.io/bodenmillergroup/steinbock:0.15.0"
```

Please note that you will need to adjust the `/path/to/data` folder to where you data is located.
After this you create a panel file directly from the MCD metadata running:

```
steinbock preprocess imc panel
```

open the generated `/path/to/data/panel.csv` file, specify which channels you want to process by adding a `1` in the `keep` column and otherwise `0` and indicate nuclear channels with a `1` in the `deepcell` column and cytoplasmic channels with a `2` in the `deepcell` column.

Image processing, cell segmentation and feature extraction is then performed via following command line calls:

```
steinbock preprocess imc images --hpf 50 

steinbock segment deepcell --minmax

steinbock measure intensities 
steinbock measure regionprops 
steinbock measure neighbors --type expansion --dmax 4
```

**Comment by jwindhager** [comment] 2023-01-13 08:41
Assuming this is resolved.

**Closed by jwindhager** 2023-01-13 08:41 UTC
